name = "day01"
description = "AoC 2025 Day 01"
version = "0.1.0-dev"

authors = ["Derek Kingston"]
maintainers = ["Derek Kingston <derek.kingston@gmail.com>"]
maintainers-logins = ["derekkingston"]
licenses = "MIT"
website = ""
tags = []

executables = ["day01"]
