name = "tryspark"
description = "Playing around with SPARK"
version = "0.1.0-dev"

authors = ["Derek Kingston"]
maintainers = ["Derek Kingston <derek.kingston@gmail.com>"]
maintainers-logins = ["derekkingston"]
licenses = "MIT"
website = ""
tags = []

executables = ["tryspark"]

[build-switches]
"*".optimization = ["-gnatX"]
"*".debug_info  = ["-gnatX"]
"*".contracts = ["-gnatX"]
"*".compile_checks = ["-gnatX"]
"*".runtime_checks = ["-gnatX"]
"*".style_checks = ["-gnatyM100"]

[[depends-on]]
gnatprove = "^15.1.0"
